name: PR Validation

on:
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: 'Deps: show dependencies metadata'
        uses: lirantal/github-action-new-dependencies-advisor@06912df98836c8698a9e7525795612b439ff7612
        if: github.event_name == 'pull_request'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: yarn
      - run: yarn lint
      - run: yarn lint:lockfile
      - run: yarn lint:firefox

  allero:
    runs-on: ubuntu-latest
    env:
      ALLERO_TOKEN: eyJydWxlcyI6W3RydWUsdHJ1ZSx0cnVlLGZhbHNlLGZhbHNlLHRydWUsdHJ1ZSx0cnVlLHRydWUsdHJ1ZSxmYWxzZSxmYWxzZSxmYWxzZSxmYWxzZSx0cnVlLHRydWUsdHJ1ZV0sInVuaXF1ZUlkIjoiZDY4OTViYzYtMDQ5NS00ZTEyLTgyNzMtNTYxMDRiNzkyNmFjIn0=

    steps:
      - uses: actions/checkout@v3
      - name: Get allero cli
        run: curl https://get.allero.io | bash
      - name: Allero Config Token
        if: ${{ env.ALLERO_TOKEN != '' }}
        run: allero config set token ${{ env.ALLERO_TOKEN }}
      - name: Run policies validation
        run: allero validate .

  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [18.x]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - run: yarn
      - run: yarn test
